// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: api/proto/location.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Shelf struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Zone          string                 `protobuf:"bytes,3,opt,name=zone,proto3" json:"zone,omitempty"`
	Rows          int32                  `protobuf:"varint,4,opt,name=rows,proto3" json:"rows,omitempty"`
	Columns       int32                  `protobuf:"varint,5,opt,name=columns,proto3" json:"columns,omitempty"`
	Levels        int32                  `protobuf:"varint,6,opt,name=levels,proto3" json:"levels,omitempty"`
	Slots         []*Slot                `protobuf:"bytes,7,rep,name=slots,proto3" json:"slots,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Shelf) Reset() {
	*x = Shelf{}
	mi := &file_api_proto_location_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Shelf) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Shelf) ProtoMessage() {}

func (x *Shelf) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_location_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Shelf.ProtoReflect.Descriptor instead.
func (*Shelf) Descriptor() ([]byte, []int) {
	return file_api_proto_location_proto_rawDescGZIP(), []int{0}
}

func (x *Shelf) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Shelf) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Shelf) GetZone() string {
	if x != nil {
		return x.Zone
	}
	return ""
}

func (x *Shelf) GetRows() int32 {
	if x != nil {
		return x.Rows
	}
	return 0
}

func (x *Shelf) GetColumns() int32 {
	if x != nil {
		return x.Columns
	}
	return 0
}

func (x *Shelf) GetLevels() int32 {
	if x != nil {
		return x.Levels
	}
	return 0
}

func (x *Shelf) GetSlots() []*Slot {
	if x != nil {
		return x.Slots
	}
	return nil
}

type Slot struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	ShelfId       string                 `protobuf:"bytes,2,opt,name=shelf_id,json=shelfId,proto3" json:"shelf_id,omitempty"`
	Row           int32                  `protobuf:"varint,3,opt,name=row,proto3" json:"row,omitempty"`
	Column        int32                  `protobuf:"varint,4,opt,name=column,proto3" json:"column,omitempty"`
	Level         int32                  `protobuf:"varint,5,opt,name=level,proto3" json:"level,omitempty"`
	Status        string                 `protobuf:"bytes,6,opt,name=status,proto3" json:"status,omitempty"`
	MaterialId    string                 `protobuf:"bytes,7,opt,name=material_id,json=materialId,proto3" json:"material_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Slot) Reset() {
	*x = Slot{}
	mi := &file_api_proto_location_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Slot) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Slot) ProtoMessage() {}

func (x *Slot) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_location_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Slot.ProtoReflect.Descriptor instead.
func (*Slot) Descriptor() ([]byte, []int) {
	return file_api_proto_location_proto_rawDescGZIP(), []int{1}
}

func (x *Slot) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Slot) GetShelfId() string {
	if x != nil {
		return x.ShelfId
	}
	return ""
}

func (x *Slot) GetRow() int32 {
	if x != nil {
		return x.Row
	}
	return 0
}

func (x *Slot) GetColumn() int32 {
	if x != nil {
		return x.Column
	}
	return 0
}

func (x *Slot) GetLevel() int32 {
	if x != nil {
		return x.Level
	}
	return 0
}

func (x *Slot) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *Slot) GetMaterialId() string {
	if x != nil {
		return x.MaterialId
	}
	return ""
}

type GetShelfLayoutRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ShelfId       string                 `protobuf:"bytes,1,opt,name=shelf_id,json=shelfId,proto3" json:"shelf_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetShelfLayoutRequest) Reset() {
	*x = GetShelfLayoutRequest{}
	mi := &file_api_proto_location_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetShelfLayoutRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetShelfLayoutRequest) ProtoMessage() {}

func (x *GetShelfLayoutRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_location_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetShelfLayoutRequest.ProtoReflect.Descriptor instead.
func (*GetShelfLayoutRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_location_proto_rawDescGZIP(), []int{2}
}

func (x *GetShelfLayoutRequest) GetShelfId() string {
	if x != nil {
		return x.ShelfId
	}
	return ""
}

type GetShelfLayoutResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Shelf         *Shelf                 `protobuf:"bytes,1,opt,name=shelf,proto3" json:"shelf,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetShelfLayoutResponse) Reset() {
	*x = GetShelfLayoutResponse{}
	mi := &file_api_proto_location_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetShelfLayoutResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetShelfLayoutResponse) ProtoMessage() {}

func (x *GetShelfLayoutResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_location_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetShelfLayoutResponse.ProtoReflect.Descriptor instead.
func (*GetShelfLayoutResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_location_proto_rawDescGZIP(), []int{3}
}

func (x *GetShelfLayoutResponse) GetShelf() *Shelf {
	if x != nil {
		return x.Shelf
	}
	return nil
}

type FindOptimalPathRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StartSlotId   string                 `protobuf:"bytes,1,opt,name=start_slot_id,json=startSlotId,proto3" json:"start_slot_id,omitempty"`
	EndSlotId     string                 `protobuf:"bytes,2,opt,name=end_slot_id,json=endSlotId,proto3" json:"end_slot_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FindOptimalPathRequest) Reset() {
	*x = FindOptimalPathRequest{}
	mi := &file_api_proto_location_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FindOptimalPathRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FindOptimalPathRequest) ProtoMessage() {}

func (x *FindOptimalPathRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_location_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FindOptimalPathRequest.ProtoReflect.Descriptor instead.
func (*FindOptimalPathRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_location_proto_rawDescGZIP(), []int{4}
}

func (x *FindOptimalPathRequest) GetStartSlotId() string {
	if x != nil {
		return x.StartSlotId
	}
	return ""
}

func (x *FindOptimalPathRequest) GetEndSlotId() string {
	if x != nil {
		return x.EndSlotId
	}
	return ""
}

type FindOptimalPathResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PathSlotIds   []string               `protobuf:"bytes,1,rep,name=path_slot_ids,json=pathSlotIds,proto3" json:"path_slot_ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FindOptimalPathResponse) Reset() {
	*x = FindOptimalPathResponse{}
	mi := &file_api_proto_location_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FindOptimalPathResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FindOptimalPathResponse) ProtoMessage() {}

func (x *FindOptimalPathResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_location_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FindOptimalPathResponse.ProtoReflect.Descriptor instead.
func (*FindOptimalPathResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_location_proto_rawDescGZIP(), []int{5}
}

func (x *FindOptimalPathResponse) GetPathSlotIds() []string {
	if x != nil {
		return x.PathSlotIds
	}
	return nil
}

type AllocateSlotRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MaterialType  string                 `protobuf:"bytes,1,opt,name=material_type,json=materialType,proto3" json:"material_type,omitempty"`
	Zone          string                 `protobuf:"bytes,2,opt,name=zone,proto3" json:"zone,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AllocateSlotRequest) Reset() {
	*x = AllocateSlotRequest{}
	mi := &file_api_proto_location_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AllocateSlotRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AllocateSlotRequest) ProtoMessage() {}

func (x *AllocateSlotRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_location_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AllocateSlotRequest.ProtoReflect.Descriptor instead.
func (*AllocateSlotRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_location_proto_rawDescGZIP(), []int{6}
}

func (x *AllocateSlotRequest) GetMaterialType() string {
	if x != nil {
		return x.MaterialType
	}
	return ""
}

func (x *AllocateSlotRequest) GetZone() string {
	if x != nil {
		return x.Zone
	}
	return ""
}

type AllocateSlotResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SlotId        string                 `protobuf:"bytes,1,opt,name=slot_id,json=slotId,proto3" json:"slot_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AllocateSlotResponse) Reset() {
	*x = AllocateSlotResponse{}
	mi := &file_api_proto_location_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AllocateSlotResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AllocateSlotResponse) ProtoMessage() {}

func (x *AllocateSlotResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_location_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AllocateSlotResponse.ProtoReflect.Descriptor instead.
func (*AllocateSlotResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_location_proto_rawDescGZIP(), []int{7}
}

func (x *AllocateSlotResponse) GetSlotId() string {
	if x != nil {
		return x.SlotId
	}
	return ""
}

var File_api_proto_location_proto protoreflect.FileDescriptor

const file_api_proto_location_proto_rawDesc = "" +
	"\n" +
	"\x18api/proto/location.proto\x12\blocation\"\xab\x01\n" +
	"\x05Shelf\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x12\n" +
	"\x04zone\x18\x03 \x01(\tR\x04zone\x12\x12\n" +
	"\x04rows\x18\x04 \x01(\x05R\x04rows\x12\x18\n" +
	"\acolumns\x18\x05 \x01(\x05R\acolumns\x12\x16\n" +
	"\x06levels\x18\x06 \x01(\x05R\x06levels\x12$\n" +
	"\x05slots\x18\a \x03(\v2\x0e.location.SlotR\x05slots\"\xaa\x01\n" +
	"\x04Slot\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x19\n" +
	"\bshelf_id\x18\x02 \x01(\tR\ashelfId\x12\x10\n" +
	"\x03row\x18\x03 \x01(\x05R\x03row\x12\x16\n" +
	"\x06column\x18\x04 \x01(\x05R\x06column\x12\x14\n" +
	"\x05level\x18\x05 \x01(\x05R\x05level\x12\x16\n" +
	"\x06status\x18\x06 \x01(\tR\x06status\x12\x1f\n" +
	"\vmaterial_id\x18\a \x01(\tR\n" +
	"materialId\"2\n" +
	"\x15GetShelfLayoutRequest\x12\x19\n" +
	"\bshelf_id\x18\x01 \x01(\tR\ashelfId\"?\n" +
	"\x16GetShelfLayoutResponse\x12%\n" +
	"\x05shelf\x18\x01 \x01(\v2\x0f.location.ShelfR\x05shelf\"\\\n" +
	"\x16FindOptimalPathRequest\x12\"\n" +
	"\rstart_slot_id\x18\x01 \x01(\tR\vstartSlotId\x12\x1e\n" +
	"\vend_slot_id\x18\x02 \x01(\tR\tendSlotId\"=\n" +
	"\x17FindOptimalPathResponse\x12\"\n" +
	"\rpath_slot_ids\x18\x01 \x03(\tR\vpathSlotIds\"N\n" +
	"\x13AllocateSlotRequest\x12#\n" +
	"\rmaterial_type\x18\x01 \x01(\tR\fmaterialType\x12\x12\n" +
	"\x04zone\x18\x02 \x01(\tR\x04zone\"/\n" +
	"\x14AllocateSlotResponse\x12\x17\n" +
	"\aslot_id\x18\x01 \x01(\tR\x06slotId2\x8d\x02\n" +
	"\x0fLocationService\x12S\n" +
	"\x0eGetShelfLayout\x12\x1f.location.GetShelfLayoutRequest\x1a .location.GetShelfLayoutResponse\x12V\n" +
	"\x0fFindOptimalPath\x12 .location.FindOptimalPathRequest\x1a!.location.FindOptimalPathResponse\x12M\n" +
	"\fAllocateSlot\x12\x1d.location.AllocateSlotRequest\x1a\x1e.location.AllocateSlotResponseBMZKgithub.com/your-repo/warehouse-management-system/location-service/api/protob\x06proto3"

var (
	file_api_proto_location_proto_rawDescOnce sync.Once
	file_api_proto_location_proto_rawDescData []byte
)

func file_api_proto_location_proto_rawDescGZIP() []byte {
	file_api_proto_location_proto_rawDescOnce.Do(func() {
		file_api_proto_location_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_proto_location_proto_rawDesc), len(file_api_proto_location_proto_rawDesc)))
	})
	return file_api_proto_location_proto_rawDescData
}

var file_api_proto_location_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_api_proto_location_proto_goTypes = []any{
	(*Shelf)(nil),                   // 0: location.Shelf
	(*Slot)(nil),                    // 1: location.Slot
	(*GetShelfLayoutRequest)(nil),   // 2: location.GetShelfLayoutRequest
	(*GetShelfLayoutResponse)(nil),  // 3: location.GetShelfLayoutResponse
	(*FindOptimalPathRequest)(nil),  // 4: location.FindOptimalPathRequest
	(*FindOptimalPathResponse)(nil), // 5: location.FindOptimalPathResponse
	(*AllocateSlotRequest)(nil),     // 6: location.AllocateSlotRequest
	(*AllocateSlotResponse)(nil),    // 7: location.AllocateSlotResponse
}
var file_api_proto_location_proto_depIdxs = []int32{
	1, // 0: location.Shelf.slots:type_name -> location.Slot
	0, // 1: location.GetShelfLayoutResponse.shelf:type_name -> location.Shelf
	2, // 2: location.LocationService.GetShelfLayout:input_type -> location.GetShelfLayoutRequest
	4, // 3: location.LocationService.FindOptimalPath:input_type -> location.FindOptimalPathRequest
	6, // 4: location.LocationService.AllocateSlot:input_type -> location.AllocateSlotRequest
	3, // 5: location.LocationService.GetShelfLayout:output_type -> location.GetShelfLayoutResponse
	5, // 6: location.LocationService.FindOptimalPath:output_type -> location.FindOptimalPathResponse
	7, // 7: location.LocationService.AllocateSlot:output_type -> location.AllocateSlotResponse
	5, // [5:8] is the sub-list for method output_type
	2, // [2:5] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_api_proto_location_proto_init() }
func file_api_proto_location_proto_init() {
	if File_api_proto_location_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_proto_location_proto_rawDesc), len(file_api_proto_location_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_proto_location_proto_goTypes,
		DependencyIndexes: file_api_proto_location_proto_depIdxs,
		MessageInfos:      file_api_proto_location_proto_msgTypes,
	}.Build()
	File_api_proto_location_proto = out.File
	file_api_proto_location_proto_goTypes = nil
	file_api_proto_location_proto_depIdxs = nil
}
