// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v5.29.3
// source: api/proto/location.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// LocationServiceClient is the client API for LocationService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type LocationServiceClient interface {
	// Get the layout of a specific shelf
	GetShelfLayout(ctx context.Context, in *GetShelfLayoutRequest, opts ...grpc.CallOption) (*ShelfLayoutResponse, error)
	// Find the optimal path between two points in the warehouse
	FindOptimalPath(ctx context.Context, in *FindOptimalPathRequest, opts ...grpc.CallOption) (*FindOptimalPathResponse, error)
	// Suggest a suitable slot for a new material
	SuggestPlacement(ctx context.Context, in *SuggestPlacementRequest, opts ...grpc.CallOption) (*SuggestPlacementResponse, error)
	// --- Admin Endpoints ---
	// Create or Update a Zone
	UpsertZone(ctx context.Context, in *Zone, opts ...grpc.CallOption) (*Zone, error)
	// Create or Update a Shelf
	UpsertShelf(ctx context.Context, in *Shelf, opts ...grpc.CallOption) (*Shelf, error)
}

type locationServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewLocationServiceClient(cc grpc.ClientConnInterface) LocationServiceClient {
	return &locationServiceClient{cc}
}

func (c *locationServiceClient) GetShelfLayout(ctx context.Context, in *GetShelfLayoutRequest, opts ...grpc.CallOption) (*ShelfLayoutResponse, error) {
	out := new(ShelfLayoutResponse)
	err := c.cc.Invoke(ctx, "/location.LocationService/GetShelfLayout", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *locationServiceClient) FindOptimalPath(ctx context.Context, in *FindOptimalPathRequest, opts ...grpc.CallOption) (*FindOptimalPathResponse, error) {
	out := new(FindOptimalPathResponse)
	err := c.cc.Invoke(ctx, "/location.LocationService/FindOptimalPath", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *locationServiceClient) SuggestPlacement(ctx context.Context, in *SuggestPlacementRequest, opts ...grpc.CallOption) (*SuggestPlacementResponse, error) {
	out := new(SuggestPlacementResponse)
	err := c.cc.Invoke(ctx, "/location.LocationService/SuggestPlacement", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *locationServiceClient) UpsertZone(ctx context.Context, in *Zone, opts ...grpc.CallOption) (*Zone, error) {
	out := new(Zone)
	err := c.cc.Invoke(ctx, "/location.LocationService/UpsertZone", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *locationServiceClient) UpsertShelf(ctx context.Context, in *Shelf, opts ...grpc.CallOption) (*Shelf, error) {
	out := new(Shelf)
	err := c.cc.Invoke(ctx, "/location.LocationService/UpsertShelf", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// LocationServiceServer is the server API for LocationService service.
// All implementations must embed UnimplementedLocationServiceServer
// for forward compatibility
type LocationServiceServer interface {
	// Get the layout of a specific shelf
	GetShelfLayout(context.Context, *GetShelfLayoutRequest) (*ShelfLayoutResponse, error)
	// Find the optimal path between two points in the warehouse
	FindOptimalPath(context.Context, *FindOptimalPathRequest) (*FindOptimalPathResponse, error)
	// Suggest a suitable slot for a new material
	SuggestPlacement(context.Context, *SuggestPlacementRequest) (*SuggestPlacementResponse, error)
	// --- Admin Endpoints ---
	// Create or Update a Zone
	UpsertZone(context.Context, *Zone) (*Zone, error)
	// Create or Update a Shelf
	UpsertShelf(context.Context, *Shelf) (*Shelf, error)
	mustEmbedUnimplementedLocationServiceServer()
}

// UnimplementedLocationServiceServer must be embedded to have forward compatible implementations.
type UnimplementedLocationServiceServer struct {
}

func (UnimplementedLocationServiceServer) GetShelfLayout(context.Context, *GetShelfLayoutRequest) (*ShelfLayoutResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetShelfLayout not implemented")
}
func (UnimplementedLocationServiceServer) FindOptimalPath(context.Context, *FindOptimalPathRequest) (*FindOptimalPathResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method FindOptimalPath not implemented")
}
func (UnimplementedLocationServiceServer) SuggestPlacement(context.Context, *SuggestPlacementRequest) (*SuggestPlacementResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SuggestPlacement not implemented")
}
func (UnimplementedLocationServiceServer) UpsertZone(context.Context, *Zone) (*Zone, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpsertZone not implemented")
}
func (UnimplementedLocationServiceServer) UpsertShelf(context.Context, *Shelf) (*Shelf, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpsertShelf not implemented")
}
func (UnimplementedLocationServiceServer) mustEmbedUnimplementedLocationServiceServer() {}

// UnsafeLocationServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to LocationServiceServer will
// result in compilation errors.
type UnsafeLocationServiceServer interface {
	mustEmbedUnimplementedLocationServiceServer()
}

func RegisterLocationServiceServer(s grpc.ServiceRegistrar, srv LocationServiceServer) {
	s.RegisterService(&LocationService_ServiceDesc, srv)
}

func _LocationService_GetShelfLayout_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetShelfLayoutRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LocationServiceServer).GetShelfLayout(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/location.LocationService/GetShelfLayout",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LocationServiceServer).GetShelfLayout(ctx, req.(*GetShelfLayoutRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LocationService_FindOptimalPath_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FindOptimalPathRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LocationServiceServer).FindOptimalPath(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/location.LocationService/FindOptimalPath",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LocationServiceServer).FindOptimalPath(ctx, req.(*FindOptimalPathRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LocationService_SuggestPlacement_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SuggestPlacementRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LocationServiceServer).SuggestPlacement(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/location.LocationService/SuggestPlacement",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LocationServiceServer).SuggestPlacement(ctx, req.(*SuggestPlacementRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LocationService_UpsertZone_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Zone)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LocationServiceServer).UpsertZone(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/location.LocationService/UpsertZone",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LocationServiceServer).UpsertZone(ctx, req.(*Zone))
	}
	return interceptor(ctx, in, info, handler)
}

func _LocationService_UpsertShelf_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Shelf)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LocationServiceServer).UpsertShelf(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/location.LocationService/UpsertShelf",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LocationServiceServer).UpsertShelf(ctx, req.(*Shelf))
	}
	return interceptor(ctx, in, info, handler)
}

// LocationService_ServiceDesc is the grpc.ServiceDesc for LocationService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var LocationService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "location.LocationService",
	HandlerType: (*LocationServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetShelfLayout",
			Handler:    _LocationService_GetShelfLayout_Handler,
		},
		{
			MethodName: "FindOptimalPath",
			Handler:    _LocationService_FindOptimalPath_Handler,
		},
		{
			MethodName: "SuggestPlacement",
			Handler:    _LocationService_SuggestPlacement_Handler,
		},
		{
			MethodName: "UpsertZone",
			Handler:    _LocationService_UpsertZone_Handler,
		},
		{
			MethodName: "UpsertShelf",
			Handler:    _LocationService_UpsertShelf_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api/proto/location.proto",
}
